// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_i2ABN5A9ywZSHawrplnJPRjOE3yejUA',
    appId: '1:1097583814966:web:cb4a7e6c35ee75d9b32b97',
    messagingSenderId: '1097583814966',
    projectId: 'img-parser-2022',
    authDomain: 'img-parser-2022.firebaseapp.com',
    storageBucket: 'img-parser-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMVZ9Ljm2JWQx7VQ7Z513poEEYW7yc38',
    appId: '1:1097583814966:android:7b7b2fcac12cdd41b32b97',
    messagingSenderId: '1097583814966',
    projectId: 'img-parser-2022',
    storageBucket: 'img-parser-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSg7MQIw7qZBVUpTOU9DU1eq7SOJgqqHA',
    appId: '1:1097583814966:ios:3130d16bb93c17a0b32b97',
    messagingSenderId: '1097583814966',
    projectId: 'img-parser-2022',
    storageBucket: 'img-parser-2022.appspot.com',
    iosClientId: '1097583814966-j2tfrvi8pakef5t2lr690jub3vhk8uc0.apps.googleusercontent.com',
    iosBundleId: 'jw.receiptApp',
  );
}
